package agency.highlysuspect.pingpingpingpingping;

import net.minecraft.network.protocol.game.*;

import java.util.HashMap;
import java.util.Map;

//big table of obfuscation mappings
public class DefaultNameTable {
	public static final Map<Class<?>, String> TABLE = new HashMap<>();
	
	//yeah yeah theres some ones that arent packets, i dont really care
	static {
		TABLE.put(ClientboundAddEntityPacket.class, "ClientboundAddEntityPacket");
		TABLE.put(ClientboundAddExperienceOrbPacket.class, "ClientboundAddExperienceOrbPacket");
		TABLE.put(ClientboundAddPlayerPacket.class, "ClientboundAddPlayerPacket");
		TABLE.put(ClientboundAnimatePacket.class, "ClientboundAnimatePacket");
		TABLE.put(ClientboundAwardStatsPacket.class, "ClientboundAwardStatsPacket");
		TABLE.put(ClientboundBlockChangedAckPacket.class, "ClientboundBlockChangedAckPacket");
		TABLE.put(ClientboundBlockDestructionPacket.class, "ClientboundBlockDestructionPacket");
		TABLE.put(ClientboundBlockEntityDataPacket.class, "ClientboundBlockEntityDataPacket");
		TABLE.put(ClientboundBlockEventPacket.class, "ClientboundBlockEventPacket");
		TABLE.put(ClientboundBlockUpdatePacket.class, "ClientboundBlockUpdatePacket");
//		TABLE.put(ClientboundBossEventPacket.1.class, "ClientboundBossEventPacket.1");
//		TABLE.put(ClientboundBossEventPacket.AddOperation.class, "ClientboundBossEventPacket");
		TABLE.put(ClientboundBossEventPacket.class, "ClientboundBossEventPacket");
		TABLE.put(ClientboundBossEventPacket.Handler.class, "ClientboundBossEventPacket.Handler");
//		TABLE.put(ClientboundBossEventPacket.Operation.class, "ClientboundBossEventPacket");
//		TABLE.put(ClientboundBossEventPacket.OperationType.class, "ClientboundBossEventPacket");
//		TABLE.put(ClientboundBossEventPacket.UpdateNameOperation.class, "ClientboundBossEventPacket");
//		TABLE.put(ClientboundBossEventPacket.UpdateProgressOperation.class, "ClientboundBossEventPacket");
//		TABLE.put(ClientboundBossEventPacket.UpdatePropertiesOperation.class, "ClientboundBossEventPacket");
//		TABLE.put(ClientboundBossEventPacket.UpdateStyleOperation.class, "ClientboundBossEventPacket");
		TABLE.put(ClientboundBundlePacket.class, "ClientboundBundlePacket (constituent packets incorporated into stats)");
		TABLE.put(ClientboundChangeDifficultyPacket.class, "ClientboundChangeDifficultyPacket");
		TABLE.put(ClientboundChunksBiomesPacket.ChunkBiomeData.class, "ClientboundChunksBiomesPacket.ChunkBiomeData");
		TABLE.put(ClientboundChunksBiomesPacket.class, "ClientboundChunksBiomesPacket");
		TABLE.put(ClientboundClearTitlesPacket.class, "ClientboundClearTitlesPacket");
//		TABLE.put(ClientboundCommandsPacket.ArgumentNodeStub.class, "ClientboundCommandsPacket");
		TABLE.put(ClientboundCommandsPacket.class, "ClientboundCommandsPacket");
//		TABLE.put(ClientboundCommandsPacket.Entry.class, "ClientboundCommandsPacket");
//		TABLE.put(ClientboundCommandsPacket.LiteralNodeStub.class, "ClientboundCommandsPacket");
//		TABLE.put(ClientboundCommandsPacket.NodeResolver.class, "ClientboundCommandsPacket");
//		TABLE.put(ClientboundCommandsPacket.NodeStub.class, "ClientboundCommandsPacket");
		TABLE.put(ClientboundCommandSuggestionsPacket.class, "ClientboundCommandSuggestionsPacket");
		TABLE.put(ClientboundContainerClosePacket.class, "ClientboundContainerClosePacket");
		TABLE.put(ClientboundContainerSetContentPacket.class, "ClientboundContainerSetContentPacket");
		TABLE.put(ClientboundContainerSetDataPacket.class, "ClientboundContainerSetDataPacket");
		TABLE.put(ClientboundContainerSetSlotPacket.class, "ClientboundContainerSetSlotPacket");
		TABLE.put(ClientboundCooldownPacket.class, "ClientboundCooldownPacket");
		TABLE.put(ClientboundCustomChatCompletionsPacket.Action.class, "ClientboundCustomChatCompletionsPacket.Action");
		TABLE.put(ClientboundCustomChatCompletionsPacket.class, "ClientboundCustomChatCompletionsPacket");
		TABLE.put(ClientboundCustomPayloadPacket.class, "ClientboundCustomPayloadPacket");
		TABLE.put(ClientboundDamageEventPacket.class, "ClientboundDamageEventPacket");
		TABLE.put(ClientboundDeleteChatPacket.class, "ClientboundDeleteChatPacket");
		TABLE.put(ClientboundDisconnectPacket.class, "ClientboundDisconnectPacket");
		TABLE.put(ClientboundDisguisedChatPacket.class, "ClientboundDisguisedChatPacket");
		TABLE.put(ClientboundEntityEventPacket.class, "ClientboundEntityEventPacket");
		TABLE.put(ClientboundExplodePacket.class, "ClientboundExplodePacket");
		TABLE.put(ClientboundForgetLevelChunkPacket.class, "ClientboundForgetLevelChunkPacket");
		TABLE.put(ClientboundGameEventPacket.class, "ClientboundGameEventPacket");
		TABLE.put(ClientboundGameEventPacket.Type.class, "ClientboundGameEventPacket.Type");
		TABLE.put(ClientboundHorseScreenOpenPacket.class, "ClientboundHorseScreenOpenPacket");
		TABLE.put(ClientboundHurtAnimationPacket.class, "ClientboundHurtAnimationPacket");
		TABLE.put(ClientboundInitializeBorderPacket.class, "ClientboundInitializeBorderPacket");
		TABLE.put(ClientboundKeepAlivePacket.class, "ClientboundKeepAlivePacket");
//		TABLE.put(ClientboundLevelChunkPacketData.BlockEntityInfo.class, "ClientboundLevelChunkPacketData");
		TABLE.put(ClientboundLevelChunkPacketData.BlockEntityTagOutput.class, "ClientboundLevelChunkPacketData.BlockEntityTagOutput");
		TABLE.put(ClientboundLevelChunkPacketData.class, "ClientboundLevelChunkPacketData");
		TABLE.put(ClientboundLevelChunkWithLightPacket.class, "ClientboundLevelChunkWithLightPacket");
		TABLE.put(ClientboundLevelEventPacket.class, "ClientboundLevelEventPacket");
		TABLE.put(ClientboundLevelParticlesPacket.class, "ClientboundLevelParticlesPacket");
		TABLE.put(ClientboundLightUpdatePacket.class, "ClientboundLightUpdatePacket");
		TABLE.put(ClientboundLightUpdatePacketData.class, "ClientboundLightUpdatePacketData");
		TABLE.put(ClientboundLoginPacket.class, "ClientboundLoginPacket");
		TABLE.put(ClientboundMapItemDataPacket.class, "ClientboundMapItemDataPacket");
		TABLE.put(ClientboundMerchantOffersPacket.class, "ClientboundMerchantOffersPacket");
		TABLE.put(ClientboundMoveEntityPacket.class, "ClientboundMoveEntityPacket");
		TABLE.put(ClientboundMoveEntityPacket.Pos.class, "ClientboundMoveEntityPacket.Pos");
		TABLE.put(ClientboundMoveEntityPacket.PosRot.class, "ClientboundMoveEntityPacket.PosRot");
		TABLE.put(ClientboundMoveEntityPacket.Rot.class, "ClientboundMoveEntityPacket.Rot");
		TABLE.put(ClientboundMoveVehiclePacket.class, "ClientboundMoveVehiclePacket");
		TABLE.put(ClientboundOpenBookPacket.class, "ClientboundOpenBookPacket");
		TABLE.put(ClientboundOpenScreenPacket.class, "ClientboundOpenScreenPacket");
		TABLE.put(ClientboundOpenSignEditorPacket.class, "ClientboundOpenSignEditorPacket");
		TABLE.put(ClientboundPingPacket.class, "ClientboundPingPacket");
		TABLE.put(ClientboundPlaceGhostRecipePacket.class, "ClientboundPlaceGhostRecipePacket");
		TABLE.put(ClientboundPlayerAbilitiesPacket.class, "ClientboundPlayerAbilitiesPacket");
		TABLE.put(ClientboundPlayerChatPacket.class, "ClientboundPlayerChatPacket");
		TABLE.put(ClientboundPlayerCombatEndPacket.class, "ClientboundPlayerCombatEndPacket");
		TABLE.put(ClientboundPlayerCombatEnterPacket.class, "ClientboundPlayerCombatEnterPacket");
		TABLE.put(ClientboundPlayerCombatKillPacket.class, "ClientboundPlayerCombatKillPacket");
		TABLE.put(ClientboundPlayerInfoRemovePacket.class, "ClientboundPlayerInfoRemovePacket");
		TABLE.put(ClientboundPlayerInfoUpdatePacket.Action.class, "ClientboundPlayerInfoUpdatePacket.Action");
		TABLE.put(ClientboundPlayerInfoUpdatePacket.Action.Reader.class, "ClientboundPlayerInfoUpdatePacket.Action.Reader");
		TABLE.put(ClientboundPlayerInfoUpdatePacket.Action.Writer.class, "ClientboundPlayerInfoUpdatePacket.Action.Writer");
		TABLE.put(ClientboundPlayerInfoUpdatePacket.class, "ClientboundPlayerInfoUpdatePacket");
//		TABLE.put(ClientboundPlayerInfoUpdatePacket.EntryBuilder.class, "ClientboundPlayerInfoUpdatePacket");
		TABLE.put(ClientboundPlayerInfoUpdatePacket.Entry.class, "ClientboundPlayerInfoUpdatePacket.Entry");
		TABLE.put(ClientboundPlayerLookAtPacket.class, "ClientboundPlayerLookAtPacket");
		TABLE.put(ClientboundPlayerPositionPacket.class, "ClientboundPlayerPositionPacket");
		TABLE.put(ClientboundRecipePacket.class, "ClientboundRecipePacket");
		TABLE.put(ClientboundRecipePacket.State.class, "ClientboundRecipePacket.State");
		TABLE.put(ClientboundRemoveEntitiesPacket.class, "ClientboundRemoveEntitiesPacket");
		TABLE.put(ClientboundRemoveMobEffectPacket.class, "ClientboundRemoveMobEffectPacket");
		TABLE.put(ClientboundResourcePackPacket.class, "ClientboundResourcePackPacket");
		TABLE.put(ClientboundRespawnPacket.class, "ClientboundRespawnPacket");
		TABLE.put(ClientboundRotateHeadPacket.class, "ClientboundRotateHeadPacket");
		TABLE.put(ClientboundSectionBlocksUpdatePacket.class, "ClientboundSectionBlocksUpdatePacket");
		TABLE.put(ClientboundSelectAdvancementsTabPacket.class, "ClientboundSelectAdvancementsTabPacket");
		TABLE.put(ClientboundServerDataPacket.class, "ClientboundServerDataPacket");
		TABLE.put(ClientboundSetActionBarTextPacket.class, "ClientboundSetActionBarTextPacket");
		TABLE.put(ClientboundSetBorderCenterPacket.class, "ClientboundSetBorderCenterPacket");
		TABLE.put(ClientboundSetBorderLerpSizePacket.class, "ClientboundSetBorderLerpSizePacket");
		TABLE.put(ClientboundSetBorderSizePacket.class, "ClientboundSetBorderSizePacket");
		TABLE.put(ClientboundSetBorderWarningDelayPacket.class, "ClientboundSetBorderWarningDelayPacket");
		TABLE.put(ClientboundSetBorderWarningDistancePacket.class, "ClientboundSetBorderWarningDistancePacket");
		TABLE.put(ClientboundSetCameraPacket.class, "ClientboundSetCameraPacket");
		TABLE.put(ClientboundSetCarriedItemPacket.class, "ClientboundSetCarriedItemPacket");
		TABLE.put(ClientboundSetChunkCacheCenterPacket.class, "ClientboundSetChunkCacheCenterPacket");
		TABLE.put(ClientboundSetChunkCacheRadiusPacket.class, "ClientboundSetChunkCacheRadiusPacket");
		TABLE.put(ClientboundSetDefaultSpawnPositionPacket.class, "ClientboundSetDefaultSpawnPositionPacket");
		TABLE.put(ClientboundSetDisplayObjectivePacket.class, "ClientboundSetDisplayObjectivePacket");
		TABLE.put(ClientboundSetEntityDataPacket.class, "ClientboundSetEntityDataPacket");
		TABLE.put(ClientboundSetEntityLinkPacket.class, "ClientboundSetEntityLinkPacket");
		TABLE.put(ClientboundSetEntityMotionPacket.class, "ClientboundSetEntityMotionPacket");
		TABLE.put(ClientboundSetEquipmentPacket.class, "ClientboundSetEquipmentPacket");
		TABLE.put(ClientboundSetExperiencePacket.class, "ClientboundSetExperiencePacket");
		TABLE.put(ClientboundSetHealthPacket.class, "ClientboundSetHealthPacket");
		TABLE.put(ClientboundSetObjectivePacket.class, "ClientboundSetObjectivePacket");
		TABLE.put(ClientboundSetPassengersPacket.class, "ClientboundSetPassengersPacket");
		TABLE.put(ClientboundSetPlayerTeamPacket.Action.class, "ClientboundSetPlayerTeamPacket.Action");
		TABLE.put(ClientboundSetPlayerTeamPacket.class, "ClientboundSetPlayerTeamPacket");
		TABLE.put(ClientboundSetPlayerTeamPacket.Parameters.class, "ClientboundSetPlayerTeamPacket.Parameters");
		TABLE.put(ClientboundSetScorePacket.class, "ClientboundSetScorePacket");
		TABLE.put(ClientboundSetSimulationDistancePacket.class, "ClientboundSetSimulationDistancePacket");
		TABLE.put(ClientboundSetSubtitleTextPacket.class, "ClientboundSetSubtitleTextPacket");
		TABLE.put(ClientboundSetTimePacket.class, "ClientboundSetTimePacket");
		TABLE.put(ClientboundSetTitlesAnimationPacket.class, "ClientboundSetTitlesAnimationPacket");
		TABLE.put(ClientboundSetTitleTextPacket.class, "ClientboundSetTitleTextPacket");
		TABLE.put(ClientboundSoundEntityPacket.class, "ClientboundSoundEntityPacket");
		TABLE.put(ClientboundSoundPacket.class, "ClientboundSoundPacket");
		TABLE.put(ClientboundStopSoundPacket.class, "ClientboundStopSoundPacket");
		TABLE.put(ClientboundSystemChatPacket.class, "ClientboundSystemChatPacket");
		TABLE.put(ClientboundTabListPacket.class, "ClientboundTabListPacket");
		TABLE.put(ClientboundTagQueryPacket.class, "ClientboundTagQueryPacket");
		TABLE.put(ClientboundTakeItemEntityPacket.class, "ClientboundTakeItemEntityPacket");
		TABLE.put(ClientboundTeleportEntityPacket.class, "ClientboundTeleportEntityPacket");
		TABLE.put(ClientboundUpdateAdvancementsPacket.class, "ClientboundUpdateAdvancementsPacket");
		TABLE.put(ClientboundUpdateAttributesPacket.AttributeSnapshot.class, "ClientboundUpdateAttributesPacket.AttributeSnapshot");
		TABLE.put(ClientboundUpdateAttributesPacket.class, "ClientboundUpdateAttributesPacket");
		TABLE.put(ClientboundUpdateEnabledFeaturesPacket.class, "ClientboundUpdateEnabledFeaturesPacket");
		TABLE.put(ClientboundUpdateMobEffectPacket.class, "ClientboundUpdateMobEffectPacket");
		TABLE.put(ClientboundUpdateRecipesPacket.class, "ClientboundUpdateRecipesPacket");
		TABLE.put(ClientboundUpdateTagsPacket.class, "ClientboundUpdateTagsPacket");
		
		TABLE.put(ServerboundAcceptTeleportationPacket.class, "ServerboundAcceptTeleportationPacket");
		TABLE.put(ServerboundBlockEntityTagQuery.class, "ServerboundBlockEntityTagQuery");
		TABLE.put(ServerboundChangeDifficultyPacket.class, "ServerboundChangeDifficultyPacket");
		TABLE.put(ServerboundChatAckPacket.class, "ServerboundChatAckPacket");
		TABLE.put(ServerboundChatCommandPacket.class, "ServerboundChatCommandPacket");
		TABLE.put(ServerboundChatPacket.class, "ServerboundChatPacket");
		TABLE.put(ServerboundChatSessionUpdatePacket.class, "ServerboundChatSessionUpdatePacket");
		TABLE.put(ServerboundClientCommandPacket.Action.class, "ServerboundClientCommandPacket$Action");
		TABLE.put(ServerboundClientCommandPacket.class, "ServerboundClientCommandPacket");
		TABLE.put(ServerboundClientInformationPacket.class, "ServerboundClientInformationPacket");
		TABLE.put(ServerboundCommandSuggestionPacket.class, "ServerboundCommandSuggestionPacket");
		TABLE.put(ServerboundContainerButtonClickPacket.class, "ServerboundContainerButtonClickPacket");
		TABLE.put(ServerboundContainerClickPacket.class, "ServerboundContainerClickPacket");
		TABLE.put(ServerboundContainerClosePacket.class, "ServerboundContainerClosePacket");
		TABLE.put(ServerboundCustomPayloadPacket.class, "ServerboundCustomPayloadPacket");
		TABLE.put(ServerboundEditBookPacket.class, "ServerboundEditBookPacket");
		TABLE.put(ServerboundEntityTagQuery.class, "ServerboundEntityTagQuery");
		//TABLE.put(ServerboundInteractPacket.1.class, "ServerboundInteractPacket$1");
		//TABLE.put(ServerboundInteractPacket.Action.class, "ServerboundInteractPacket$Action");
		//TABLE.put(ServerboundInteractPacket.ActionType.class, "ServerboundInteractPacket$ActionType");
		TABLE.put(ServerboundInteractPacket.class, "ServerboundInteractPacket");
		TABLE.put(ServerboundInteractPacket.Handler.class, "ServerboundInteractPacket$Handler");
		//TABLE.put(ServerboundInteractPacket.InteractionAction.class, "ServerboundInteractPacket$InteractionAction");
		//TABLE.put(ServerboundInteractPacket.InteractionAtLocationAction.class, "ServerboundInteractPacket$InteractionAtLocationAction");
		TABLE.put(ServerboundJigsawGeneratePacket.class, "ServerboundJigsawGeneratePacket");
		TABLE.put(ServerboundKeepAlivePacket.class, "ServerboundKeepAlivePacket");
		TABLE.put(ServerboundLockDifficultyPacket.class, "ServerboundLockDifficultyPacket");
		TABLE.put(ServerboundMovePlayerPacket.class, "ServerboundMovePlayerPacket");
		TABLE.put(ServerboundMovePlayerPacket.Pos.class, "ServerboundMovePlayerPacket$Pos");
		TABLE.put(ServerboundMovePlayerPacket.PosRot.class, "ServerboundMovePlayerPacket$PosRot");
		TABLE.put(ServerboundMovePlayerPacket.Rot.class, "ServerboundMovePlayerPacket$Rot");
		TABLE.put(ServerboundMovePlayerPacket.StatusOnly.class, "ServerboundMovePlayerPacket$StatusOnly");
		TABLE.put(ServerboundMoveVehiclePacket.class, "ServerboundMoveVehiclePacket");
		TABLE.put(ServerboundPaddleBoatPacket.class, "ServerboundPaddleBoatPacket");
		TABLE.put(ServerboundPickItemPacket.class, "ServerboundPickItemPacket");
		TABLE.put(ServerboundPlaceRecipePacket.class, "ServerboundPlaceRecipePacket");
		TABLE.put(ServerboundPlayerAbilitiesPacket.class, "ServerboundPlayerAbilitiesPacket");
		TABLE.put(ServerboundPlayerActionPacket.Action.class, "ServerboundPlayerActionPacket$Action");
		TABLE.put(ServerboundPlayerActionPacket.class, "ServerboundPlayerActionPacket");
		TABLE.put(ServerboundPlayerCommandPacket.Action.class, "ServerboundPlayerCommandPacket$Action");
		TABLE.put(ServerboundPlayerCommandPacket.class, "ServerboundPlayerCommandPacket");
		TABLE.put(ServerboundPlayerInputPacket.class, "ServerboundPlayerInputPacket");
		TABLE.put(ServerboundPongPacket.class, "ServerboundPongPacket");
		TABLE.put(ServerboundRecipeBookChangeSettingsPacket.class, "ServerboundRecipeBookChangeSettingsPacket");
		TABLE.put(ServerboundRecipeBookSeenRecipePacket.class, "ServerboundRecipeBookSeenRecipePacket");
		TABLE.put(ServerboundRenameItemPacket.class, "ServerboundRenameItemPacket");
		TABLE.put(ServerboundResourcePackPacket.Action.class, "ServerboundResourcePackPacket$Action");
		TABLE.put(ServerboundResourcePackPacket.class, "ServerboundResourcePackPacket");
		TABLE.put(ServerboundSeenAdvancementsPacket.Action.class, "ServerboundSeenAdvancementsPacket$Action");
		TABLE.put(ServerboundSeenAdvancementsPacket.class, "ServerboundSeenAdvancementsPacket");
		TABLE.put(ServerboundSelectTradePacket.class, "ServerboundSelectTradePacket");
		TABLE.put(ServerboundSetBeaconPacket.class, "ServerboundSetBeaconPacket");
		TABLE.put(ServerboundSetCarriedItemPacket.class, "ServerboundSetCarriedItemPacket");
		TABLE.put(ServerboundSetCommandBlockPacket.class, "ServerboundSetCommandBlockPacket");
		TABLE.put(ServerboundSetCommandMinecartPacket.class, "ServerboundSetCommandMinecartPacket");
		TABLE.put(ServerboundSetCreativeModeSlotPacket.class, "ServerboundSetCreativeModeSlotPacket");
		TABLE.put(ServerboundSetJigsawBlockPacket.class, "ServerboundSetJigsawBlockPacket");
		TABLE.put(ServerboundSetStructureBlockPacket.class, "ServerboundSetStructureBlockPacket");
		TABLE.put(ServerboundSignUpdatePacket.class, "ServerboundSignUpdatePacket");
		TABLE.put(ServerboundSwingPacket.class, "ServerboundSwingPacket");
		TABLE.put(ServerboundTeleportToEntityPacket.class, "ServerboundTeleportToEntityPacket");
		TABLE.put(ServerboundUseItemOnPacket.class, "ServerboundUseItemOnPacket");
		TABLE.put(ServerboundUseItemPacket.class, "ServerboundUseItemPacket");
		TABLE.put(ServerGamePacketListener.class, "ServerGamePacketListener");
		TABLE.put(ServerPacketListener.class, "ServerPacketListener");
	}
}
